name: Create preview environment

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  # Enable manual trigger for easy debugging
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    # 1/2. 👆 Uncomment above & comment line below 👇
    # runs-on: dagger-runner
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/checkout@v3
      - name: Create preview environment
        working-directory: ./dagger
        id: create_preview_env
        run: |
          npm ci
          OUTPUT=$(node --loader ts-node/esm create.mts)
          echo "::set-output name=preview_url::$OUTPUT"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Add comment
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{ steps.create_preview_env.outputs.preview_url }}'
            })
          # 2/2. 👇 (Un)comment line below
          # _EXPERIMENTAL_DAGGER_RUNNER_HOST: "unix:///var/run/buildkit/buildkitd.sock"
